arrowParens: 'always'
bracketSameLine: false
bracketSpacing: true
endOfLine: 'crlf'
eslintIntegration: true
printWidth: 120
trailingComma: 'es5'
tabWidth: 2
semi: true
singleQuote: true
useTabs: true

