# Generated by Django 4.1.1 on 2022-12-05 09:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=core.models.Document.upload_to)),
                ('path', models.CharField(max_length=4000)),
                ('last_modified', models.DateTimeField()),
                ('name', models.CharField(max_length=1000)),
                ('size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=4000)),
                ('user', models.CharField(max_length=4000)),
                ('upload_datetime', models.DateTimeField()),
            ],
        ),
    ]
