# Generated by Django 4.1.1 on 2022-12-05 10:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(max_length=4000, upload_to=core.models.Document.upload_to),
        ),
    ]
